name: tinybird

on:
  push:
    branches:
      - '!master'

jobs:
  run_tests_tinybird:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: pip packages
      run: | 
        pip install tinybird-cli
        pip install PyYAML

    - name: version
      run: tb --version

    #- name: drop-prev-resources
    #  run: ./scripts/drop_all.sh
    #  env:
    #    TOKEN: ${{ secrets.tb_token }}

    - name: push_changes
      run: ./scripts/push_changes.sh
      env:
        TB_TOKEN: ${{ secrets.tb_token }}    

    - name: push-project
      run: tb push --push-deps --force --fixtures --no-check
      env:
        TB_TOKEN: ${{ secrets.tb_token }}

    - name: tests
      run: python test.py
      env:
        TB_TOKEN: ${{ secrets.tb_token }}

  tinybird_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: run_tests_tinybird
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: pip packages
      run: pip install tinybird-cli

    - name: info
      run: tb --version && tb workspace current
      env:
        TB_TOKEN: ${{ secrets.tb_pro_token }}

    - name: deploy
      run: tb push --push-deps --yes --force --fixtures --no-check
      env:
        TB_TOKEN: ${{ secrets.tb_pro_token }}